name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    docs: 'test'

runs:
  using: "docker"
  image: "ghcr.io/annaliseai/annalise-confluence-junction:latest"
    
branding:
  icon: "mic"
  color: "purple"
