name: A workflow for my Hello World file
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Get Job Url
      run: |
        GITHUB_JOB_ID="$(curl -fsSL -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs?per_page=100" | \
          jq ".jobs[] | select( .name == \"$GITHUB_JOB\") | .id")"
        if [ -z "$GITHUB_JOB_ID" ]; then
          printf "failed to query GITHUB_JOB_ID" >&2
          exit 1
        fi
    - name: Set Build Info and Enviroment
      id:  build-info-and-enviroment
      run: echo https://${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ steps.jobs.outputs.html_url }}